services:
  docs:
    image: tailwind_webpack_docker_local_docs
    container_name: tailwind_webpack_docker_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./tailwind_webpack_docker:/app/tailwind_webpack_docker:z
    ports:
      - '9000:9000'
    command: /start-docs
